const defaultRules = [
  {
    id: "rule-001",
    name: "SQL Injection",
    description: "Detects SQL injection signatures in request input",
    severity: "critical",
    category: "injection",
    pattern: "(\\b(SELECT|INSERT|UPDATE|DELETE|DROP|UNION)\\b.*\\b(FROM|INTO|WHERE)\\b|--|'--)",
    targets: ["body", "query", "headers"],
  },
  {
    id: "rule-002",
    name: "XSS",
    description: "Detects script and browser execution vectors",
    severity: "high",
    category: "xss",
    pattern: "(<script|javascript:|on\\w+\\s*=|eval\\s*\\(|document\\.cookie)",
    targets: ["body", "query", "headers"],
  },
  {
    id: "rule-003",
    name: "Path Traversal",
    description: "Detects parent directory traversal tokens",
    severity: "high",
    category: "traversal",
    pattern: "(\\.\\.\\/|\\.\\.\\\\|%2e%2e)",
    targets: ["query", "path"],
  },
  {
    id: "rule-004",
    name: "Command Injection",
    description: "Detects shell command chaining in input",
    severity: "critical",
    category: "injection",
    pattern: "(\\||;|`|\\$\\()\\s*(ls|cat|rm|wget|curl|bash|sh)",
    targets: ["body", "query"],
  },
  {
    id: "rule-005",
    name: "Bad Bot / Scanner",
    description: "Detects known scanner and exploit tooling user agents",
    severity: "medium",
    category: "bot",
    pattern: "(sqlmap|nikto|nmap|dirbuster|burpsuite|acunetix)",
    targets: ["headers"],
  },
  {
    id: "rule-006",
    name: "XXE Injection",
    description: "Detects external entity declarations in XML payloads",
    severity: "high",
    category: "injection",
    pattern: "<!ENTITY|<!DOCTYPE[^>]*\\[",
    targets: ["body"],
  },
  {
    id: "rule-007",
    name: "SSRF",
    description: "Detects internal address probing and metadata paths",
    severity: "high",
    category: "ssrf",
    pattern: "(localhost|127\\.0\\.0\\.1|169\\.254\\.169\\.254)",
    targets: ["body", "query"],
  },
  {
    id: "rule-008",
    name: "Sensitive Files",
    description: "Detects requests for sensitive system/application files",
    severity: "medium",
    category: "recon",
    pattern: "(\\/etc\\/passwd|\\.env|\\.git\\/config|wp-config\\.php)",
    targets: ["path", "query"],
  },
  {
    id: "rule-009",
    name: "Log4Shell",
    description: "Detects JNDI lookup exploit payloads",
    severity: "critical",
    category: "injection",
    pattern: "\\$\\{jndi:(ldap|rmi|dns)",
    targets: ["body", "query", "headers"],
  },
  {
    id: "rule-010",
    name: "Open Redirect",
    description: "Detects suspicious off-site redirect destinations",
    severity: "medium",
    category: "redirect",
    pattern: "(https?:\\/\\/(?!localhost)[^/]+\\.(evil|hack|malware))",
    targets: ["query", "body"],
  },
  {
    id: "rule-011",
    name: "HTTP Header Injection",
    description: "Detects response header splitting in payloads",
    severity: "high",
    category: "injection",
    pattern: "(\\r\\n|\\r|\\n)\\s*(Content-Type|Location|Set-Cookie):",
    targets: ["body", "query", "headers"],
  },
  {
    id: "rule-012",
    name: "Rate Limit Exceeded",
    description: "Automated rule for excessive requests per source IP",
    severity: "medium",
    category: "ratelimit",
    pattern: null,
    targets: ["ip"],
  },
];

module.exports = { defaultRules };